# Generated by Django 4.2.1 on 2023-06-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id_carrito', models.AutoField(db_column='id_producto', primary_key=True, serialize=False, verbose_name='ID_producto')),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id_comuna', models.AutoField(db_column='id_comuna', primary_key=True, serialize=False, verbose_name='ID_comuna')),
                ('comuna', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False, verbose_name='ID_producto')),
                ('nombre_producto', models.CharField(max_length=20)),
                ('descripcion_producto', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
                ('metros', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id_region', models.AutoField(db_column='id_region', primary_key=True, serialize=False, verbose_name='ID_region')),
                ('region', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id_tipo', models.AutoField(db_column='id_tipo', primary_key=True, serialize=False, verbose_name='ID_tipo_Usuario')),
                ('tipo_usuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(max_length=10)),
                ('dv_usuario', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=25)),
                ('snombre', models.CharField(blank=True, max_length=25, null=True)),
                ('appaterno', models.CharField(max_length=25)),
                ('apmaterno', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_usuario', models.CharField(max_length=50)),
                ('contra_usuario', models.CharField(max_length=50)),
                ('direccion_usuario', models.CharField(max_length=50)),
                ('activo', models.IntegerField()),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='impekbles.comuna')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='impekbles.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='producto_carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('total', models.IntegerField()),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='impekbles.carrito')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='impekbles.producto')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='impekbles.region'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='impekbles.usuario'),
        ),
    ]
