# Generated by Django 4.2.1 on 2023-06-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impekbles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='comuna',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=70),
        ),
    ]
