# Generated by Django 4.2.1 on 2023-07-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impekbles', '0002_alter_comuna_comuna_alter_region_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
