# Generated by Django 4.2.1 on 2023-07-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impekbles', '0004_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
