# Generated by Django 4.2.1 on 2023-07-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impekbles', '0005_remove_usuario_imagen_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='metros',
            field=models.FloatField(),
        ),
    ]
