# Generated by Django 4.2.1 on 2023-07-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impekbles', '0006_alter_producto_metros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_comuna',
        ),
        migrations.AddField(
            model_name='usuario',
            name='comuna_usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='region_usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='comuna',
        ),
        migrations.DeleteModel(
            name='region',
        ),
    ]
